Repository einDamian/discrete-choice, pull requests merged in 2023-08, with the labels that each got.

#76 possible fix for the offset problem
  src/config.py
Labels: bug

#72 choice error report & kleiner Kommentar fix
  src/controller/calculation/ConfigurationController.py
  src/model/Project.py
  src/model/ProjectSnapshot.py
  src/model/ProxyProject.py
  src/model/processing/VariedLogitBiogemeConfig.py
  src/view/ProcessingWidget.py
Labels: bug

#91 BugFixes EvaluationWidget
  src/view/EvaluationWidget.py
Labels: bug, question

#95 Bugfix set_config_settings for undo/redo feature
  src/model/ProjectSnapshot.py
Labels: bug

#100 Fixing undo/redo
  src/view/ProcessingWidget.py
Labels: bug

#99 Improve derivative alternative addition
  src/config.py
  src/controller/functions/AlternativeController.py
  src/controller/functions/DerivativeController.py
  src/view/ColumnWidget.py
  src/view/ConfirmationDialog.py
  src/view/ModelWidget.py
  src/view/UserInputDialog.py
Labels: enhancement, question

#98 Improve GUI for better user experince
  src/config.py
  src/controller/ProjectManager.py
  src/user_manual.pdf
  src/view/HelpMenu.py
  src/view/MainWindow.py
  src/view/NotificationBanner.py
  src/view/ui/columns.ui
  src/view/ui/evaluation.ui
  src/view/ui/main.ui
  src/view/ui/model.ui
Labels: enhancement, help wanted, question
